---
name: Primer workflow
on:
  push:
    branches:
      - Antony
jobs:
  Prueba:
    runs-on: ubuntu-latest
    permissions:
      id-token: read
      contents: read
    steps:
      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: AKIAZBSJAV3SABBM7WG4
          aws-secret-access-key: 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
          aws-region: us-east-1

